### ISSUE TITLE
ImportError: MagickWand shared library not found.

### ISSUE THREAD

**Issue by pidugusundeep** [lucab85/PDFtoTXT#1]
Traceback (most recent call last):
```
  File "/Users/pidugu/Documents/OPENCV/PDFtoTXT-master/CloudOCR.py", line 4, in <module>
    from wand.image import Image
  File "/usr/local/lib/python2.7/site-packages/wand/image.py", line 20, in <module>
    from .api import MagickPixelPacket, libc, libmagick, library
  File "/usr/local/lib/python2.7/site-packages/wand/api.py", line 210, in <module>
    'Try to install:\n  ' + msg)
```
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  brew install freetype imagemagick

Even tried installing imagemagick and it always promps me that its already installed and up to date 
```
$ brew install freetype imagemagick
Updating Homebrew...
Warning: freetype 2.9.1 is already installed and up-to-date
To reinstall 2.9.1, run `brew reinstall freetype`
Warning: imagemagick 7.0.8-14 is already installed and up-to-date
To reinstall 7.0.8-14, run `brew reinstall imagemagick`
```

**Comment by danielmaydsu** [comment]
Just out of curiosity, after you installed the packages did you do a pip install -r of the requirements.txt?

**Comment by pidugusundeep** [comment]
> Just out of curiosity, after you installed the packages did you do a pip install -r of the requirements.txt?

Yeah i did that
